### PR TITLE
Make bulk_validator nested to parse sub params properly and always return true

### PR DESCRIPTION
**Pull request by huaaaan**

### CODE REVIEW

**Review by AzRu — COMMENTED** [review]
Since you're making changes here, can you see how things will end up looking in the docs?

This is how it is right now. Ideally we can have the proper body being shown
image

**Comment by huaaaan** [comment]
> Since you're making changes here, can you see how things will end up looking in the docs?
> 
> This is how it is right now. Ideally we can have the proper body being shown image

Do I have to merge this first and update the gemfile in our repo to see it?

**Comment by AzRu** [comment]
> > Since you're making changes here, can you see how things will end up looking in the docs?
> > This is how it is right now. Ideally we can have the proper body being shown image
> 
> Do I have to merge this first and update the gemfile in our repo to see it?

No you can update the gemfile to use your branch and commit

**Comment by huaaaan** [comment]
Right now it is Screen Shot 2021-10-22 at 1 34 39 PM
, will modify the doc generator for the new validator too

**Pull request closed without merging**
